
export const GET_AUTH_TOKEN_REQUEST = 'GET_AUTH_TOKEN_REQUEST';
export const GET_AUTH_TOKEN_SUCCESS = 'GET_AUTH_TOKEN_SUCCESS';
export const GET_AUTH_TOKEN_FAILURE = 'GET_AUTH_TOKEN_FAILURE';


export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';