

export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const GET_TODOS_ERROR = 'GET_TODOS_ERROR';


export const ADD_TODOS_REQUEST = 'ADD_TODOS_REQUEST';
export const ADD_TODOS_SUCCESS = 'ADD_TODOS_SUCCESS';
export const ADD_TODOS_ERROR = 'ADD_TODOS_ERROR';


export const GET_SINGLE_TODO_REQUEST = 'GET_SINGLE_TODO_REQUEST';
export const GET_SINGLE_TODO_SUCCESS = 'GET_SINGLE_TODO_SUCCESS';
export const GET_SINGLE_TODO_FAILURE = 'GET_SINGLE_TODO_FAILURE';


export const CHANGE_SINGLE_TODO_STATUS_REQUEST = 'CHANGE_SINGLE_TODO_STATUS_REQUEST';
export const CHANGE_SINGLE_TODO_STATUS_SUCCESS = 'CHANGE_SINGLE_TODO_STATUS_SUCCESS';
export const CHANGE_SINGLE_TODO_STATUS_FAILURE = 'CHANGE_SINGLE_TODO_STATUS_FAILURE';


export const EDIT_SINGLE_TODO_REQUEST = 'EDIT_SINGLE_TODO_REQUEST';
export const EDIT_SINGLE_TODO_SUCCESS = 'EDIT_SINGLE_TODO_SUCCESS';
export const EDIT_SINGLE_TODO_FAILURE = 'EDIT_SINGLE_TODO_FAILURE';


export const DELETE_SINGLE_TODO_REQUEST = 'DELETE_SINGLE_TODO_REQUEST';
export const DELETE_SINGLE_TODO_SUCCESS = 'DELETE_SINGLE_TODO_SUCCESS';
export const DELETE_SINGLE_TODO_FAILURE = 'DELETE_SINGLE_TODO_FAILURE';


export const ADD_TOTAL_TODOS = 'ADD_TOTAL_TODOS';
export const REDUCE_TOTAL_TODOS = 'REDUCE_TOTAL_TODOS';
export const GET_TOTAL_TODOS = 'GET_TOTAL_TODOS';

export const ADD_TOTAL_COMPLETED_TODOS = 'ADD_TOTAL_COMPLETED_TODO';
export const REDUCE_TOTAL_COMPLETED_TODOS = 'REDUCE_TOTAL_COMPLETED_TODOS';
export const GET_TOTAL_COMPLETED_TODOS = 'GET_TOTAL_COMPLETED_TODOS';