export const GET_TODO_LOADING = "GET_TODO_LOADING";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const GET_TODO_FAILURE = "GET_TODO_SUCCESS";

export const POST_TODO_LOADING = "POST_TODO_LOADING";
export const POST_TODO_SUCCESS = "POST_TODO_SUCCESS";
export const POST_TODO_FAILURE = "POST_TODO_SUCCESS";

export const EDIT_TODO_LOADING = "EDIT_TODO_LOADING";
export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS";
export const EDIT_TODO_FAILURE = "EDIT_TODO_SUCCESS";

export const REMOVE_TODO_LOADING = "REMOVE_TODO_LOADING";
export const REMOVE_TODO_SUCCESS = "REMOVE_TODO_SUCCESS";
export const REMOVE_TODO_FAILURE = "REMOVE_TODO_SUCCESS";

export const TOGGLE_TODO_LOADING = "TOGGLE_TODO_LOADING";
export const TOGGLE_TODO_SUCCESS = "TOGGLE_TODO_SUCCESS";
export const TOGGLE_TODO_FAILURE = "TOGGLE_TODO_SUCCESS";
